package Cliente.Vista;

import Cliente.Modelo.ProxyCliente;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ARMC3PO
 */
public class vistaSeleccion extends javax.swing.JFrame {

    /**
     * Creates new form vistaSelecciónNumero
     */
    public vistaSeleccion() {
        initComponents();
    }

    public JPanel getPanelSeleccionSimbolo() {
        return PanelSeleccionSimbolo;
    }

    public void setPanelSeleccionSimbolo(JPanel PanelSeleccionSimbolo) {
        this.PanelSeleccionSimbolo = PanelSeleccionSimbolo;
    }


    public JButton getEnviarNumeroBTN() {
        return enviarNumeroBTN;
    }

    public void setEnviarNumeroBTN(JButton enviarNumeroBTN) {
        this.enviarNumeroBTN = enviarNumeroBTN;
    }

    public JButton getEnviarSimboloBTN() {
        return enviarSimboloBTN;
    }

    public void setEnviarSimboloBTN(JButton enviarSimboloBTN) {
        this.enviarSimboloBTN = enviarSimboloBTN;
    }

    public JLabel getEstadoContrincanteLBL() {
        return estadoContrincanteLBL;
    }

    public void setEstadoContrincanteLBL(JLabel estadoContrincanteLBL) {
        this.estadoContrincanteLBL = estadoContrincanteLBL;
    }

    public JPanel getPanelSeleccionNumero() {
        return panelSeleccionNumero;
    }

    public void setPanelSeleccionNumero(JPanel panelSeleccionNumero) {
        this.panelSeleccionNumero = panelSeleccionNumero;
    }

    public JTextField getTextoNumeroUnoAlCien() {
        return textoNumeroUnoAlCien;
    }

    public void setTextoNumeroUnoAlCien(JTextField textoNumeroUnoAlCien) {
        this.textoNumeroUnoAlCien = textoNumeroUnoAlCien;
    }

    public JTextField getTextoSimbolo() {
        return textoSimbolo;
    }

    public void setTextoSimbolo(JTextField textoSimbolo) {
        this.textoSimbolo = textoSimbolo;
    }

    public JLabel getTextoSimboloLBL() {
        return textoSimboloLBL;
    }

    public void setTextoSimboloLBL(JLabel textoSimboloLBL) {
        this.textoSimboloLBL = textoSimboloLBL;
    }

    public JLabel getTextoUnoAlCienLBL() {
        return textoUnoAlCienLBL;
    }

    public void setTextoUnoAlCienLBL(JLabel textoUnoAlCienLBL) {
        this.textoUnoAlCienLBL = textoUnoAlCienLBL;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSeleccionNumero = new javax.swing.JPanel();
        textoUnoAlCienLBL = new javax.swing.JLabel();
        textoNumeroUnoAlCien = new javax.swing.JTextField();
        enviarNumeroBTN = new javax.swing.JButton();
        PanelSeleccionSimbolo = new javax.swing.JPanel();
        textoSimboloLBL = new javax.swing.JLabel();
        textoSimbolo = new javax.swing.JTextField();
        enviarSimboloBTN = new javax.swing.JButton();
        estadoContrincanteLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoUnoAlCienLBL.setText("Ingresa un número del 1 al 100");

        textoNumeroUnoAlCien.setText("1");

        enviarNumeroBTN.setText("Enviar");
        enviarNumeroBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarNumeroBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSeleccionNumeroLayout = new javax.swing.GroupLayout(panelSeleccionNumero);
        panelSeleccionNumero.setLayout(panelSeleccionNumeroLayout);
        panelSeleccionNumeroLayout.setHorizontalGroup(
            panelSeleccionNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionNumeroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSeleccionNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeleccionNumeroLayout.createSequentialGroup()
                        .addComponent(textoUnoAlCienLBL)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeleccionNumeroLayout.createSequentialGroup()
                        .addComponent(textoNumeroUnoAlCien, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))))
            .addGroup(panelSeleccionNumeroLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(enviarNumeroBTN)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelSeleccionNumeroLayout.setVerticalGroup(
            panelSeleccionNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionNumeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoUnoAlCienLBL)
                .addGap(18, 18, 18)
                .addComponent(textoNumeroUnoAlCien, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enviarNumeroBTN)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        textoSimboloLBL.setText("Ingresa X o O para seleccionar tu símbolo");

        textoSimbolo.setText("1");

        enviarSimboloBTN.setText("Enviar");

        estadoContrincanteLBL.setForeground(new java.awt.Color(166, 92, 27));
        estadoContrincanteLBL.setText("(Tu contrincante aún no slecciona nada)");

        javax.swing.GroupLayout PanelSeleccionSimboloLayout = new javax.swing.GroupLayout(PanelSeleccionSimbolo);
        PanelSeleccionSimbolo.setLayout(PanelSeleccionSimboloLayout);
        PanelSeleccionSimboloLayout.setHorizontalGroup(
            PanelSeleccionSimboloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeleccionSimboloLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(enviarSimboloBTN)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSeleccionSimboloLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(PanelSeleccionSimboloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoSimboloLBL)
                    .addGroup(PanelSeleccionSimboloLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(PanelSeleccionSimboloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estadoContrincanteLBL)
                            .addComponent(textoSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(160, 160, 160))
        );
        PanelSeleccionSimboloLayout.setVerticalGroup(
            PanelSeleccionSimboloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeleccionSimboloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoSimboloLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estadoContrincanteLBL)
                .addGap(6, 6, 6)
                .addComponent(textoSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviarSimboloBTN)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSeleccionNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelSeleccionSimbolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(panelSeleccionNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelSeleccionSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarNumeroBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarNumeroBTNActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            PanelSeleccionSimbolo.setVisible(false);
            ProxyCliente pc = new ProxyCliente();
            String respuesta = pc.mandarMensajeAlServidor("SOLICITUD");
            System.out.println(respuesta);
            PanelSeleccionSimbolo.setVisible(true);
            
            Thread.sleep(5000);
            vistaSeleccion seleccion = new vistaSeleccion();
            seleccion.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(vistaConexion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(vistaConexion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_enviarNumeroBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Wundo".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaSeleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelSeleccionSimbolo;
    private javax.swing.JButton enviarNumeroBTN;
    private javax.swing.JButton enviarSimboloBTN;
    private javax.swing.JLabel estadoContrincanteLBL;
    private javax.swing.JPanel panelSeleccionNumero;
    private javax.swing.JTextField textoNumeroUnoAlCien;
    private javax.swing.JTextField textoSimbolo;
    private javax.swing.JLabel textoSimboloLBL;
    private javax.swing.JLabel textoUnoAlCienLBL;
    // End of variables declaration//GEN-END:variables
}
